gui:
  branchColors:
    'develop': '#11aaff' # use a light blue for main branches
    'master': '#24b372'
    'staging': '#66D9EF'
    'feature': '#A6E22E'
    'hotfix': '#CB064D'
    'fixbug': '#CB064D'
  nerdFontsVersion: "3"
  scrollHeight: 5 # how many lines you scroll by
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commitPrefix:
    - pattern: "^(\\w+)/([\\w-]+)$" # A more general match for any leading word
      replace: '[$2]: '
  mainBranches: [master, develop]
os:
  copyToClipboardCmd: echo {{text}} | lemonade copy --host=127.0.0.1
  editPreset: 'nvim'
notARepository: 'skip'
promptToReturnFromSubprocess: false
